modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="sockets" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Sockets" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
credits="Thanks for Forge being awesome." #optional
authors="Nukeologist/Lord_Archimonde" #optional
description='''Fun and games!  Adds Gems and makes some items have sockets that you may put gems inside, similar to some ARPGS.'''
[[dependencies.sockets]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31.1.18,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.sockets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.17)"
    ordering="NONE"
    side="BOTH"
